services:
  nginx:
    image: nginx:latest
    ports:
    - 8884:80
    volumes:
    - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
    - php

  php:
    image: php:8.3-fpm
    expose:
    - 9000
    volumes:
    - ./:/usr/share/nginx/html/
