# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

services:
###########################
# Setup the Nginx container
###########################
  nginx:
    image: nginx:latest
    ports:
    - 8884:80
    volumes:
    - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
    - php

###########################
# Setup the PHP container
###########################
  php:
    image: php:7.2-fpm
    expose:
    - 9000
    volumes:
    - ./:/usr/share/nginx/html/
